# get api_id & api_hash from my.telegram.org
api_id: '21523142'
api_hash: '7b2f9d6b92e21fa8968e3197aea4868e'
# 13 digit channel id startswith - like -111.......
dump_id: '-1002021598680'
# genrate session of ur tg ac for telethon run sessionmaker.py
string_session: '1AZWarzQBuwVL3HKJxgEdccQxAK0DjbYbFHrB9MiFN_vbOQohXeKQEKy_V7q9zwOLprJSnjzbjNFfdY52u_8ZKrEiuSk12Je1JLhYtS4P9nScifGWskDmjG3mpYTiggIzZ_jccp4AEQuigjcBSUW8dwaY6xihNR5WfjggXxgAw1W8uDDZtKEffyIGO2CNNJMrCdr9Q7UDoESaFuhiiU8YfuyaRkhNy1_m8U6EYonkA5tw1jJ4wT0KqZ07hDbtQyi8h5hRCAUD1pskMt7Yx6h_c1ZHFcWySGEs5lWyXDaAWTpwWclLu9qG-glqeRC41avY-XiA3SI0HXUmnacGJH_RHNWl30pFCWo='
